# Site settings
name: ogaclejapan
description: "Android Software Engineer at AbemaTV"
url: "http://ogaclejapan.com"
lang: ja
timezone: Asia/Tokyo


# Delete the lines you don't need
email: ogaclejapan@gmail.com
github_username: ogaclejapan
twitter_username: ogaclejapan
medium_username: ogaclejapan
# If you don't have a blog page delete the next line
blog_url: "http://blog.ogaclejapan.com/"


avatar: yes
avatar_img_path: "https://avatars2.githubusercontent.com/u/1496485"

front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

# Exclude Files
exclude: ["README.md", ".gitignore", "Gemfile", "Gemfile.lock", "vendor", ".travis.yml"]

